name: test-environment
channels:
  - astra-toolbox
  - dgursoy
dependencies:
  - python=2.7
  - numpy
  - scipy
  - pytest
  - h5py
  - pep8
  - mpi4py 
  - scikit-image
  - astra-toolbox
  - xraylib
  - tomopy
  - pip:
    - mock
    - fabio 
    - pytest-cov
    - coveralls
    - pyFAI 
    - nvidia-ml-py
    - pyfftw
    - peakutils
    - pymca
    - colorama

