{% set version = "1.10.0" %}
{% set release = "hdf5-1.10" %}
{% set patch = "hdf5-1.10.0-patch1" %}
#{% set filename = "hdf5-1.8.15" %} # change this

package:
  name: hdf5
  version: {{ version }}

source:
  fn: {{ patch }}.tar.bz2
  #fn: hdf5-{{ version }}.tar.bz2
  #url: https://www.hdfgroup.org/ftp/HDF5/releases/{{ filename }}-patch1/src/{{ filename }}-patch1.tar.bz2
  url: https://www.hdfgroup.org/ftp/HDF5/releases/{{ release }}/{{ patch }}/src/{{ patch }}.tar.bz2
  #md5: b060bb137d6bd8accf8f0c4c59d2746d

build:
  number: 100

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)

